[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs-22_x"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"